@startuml
actor "Port Manager" as Adm
participant ":WarningShipUI" as System
participant ":WarningShipController" as SSC
participant ":US309" as us
participant ":FileOperation" as f

autonumber

activate Adm

Adm -> System: regist a cargo manifest for a particular ship on a date when the ship is already occupied

activate System

System -> SSC: createUS309

activate SSC

SSC -> us: demo(INSERT)

activate us

us -> us: initialize

us -> f: WriteToAFile(e.getMessage)

deactivate us

activate f

f --> SSC: file

deactivate f

SSC --> System: file

System --> Adm: shows the requested data

deactivate SSC

deactivate System

deactivate Adm
@enduml