@startuml
actor "Traffic Manager" as Adm
participant "System" as System

autonumber

activate Adm

Adm -> System: regist a cargo manifest for a particular ship on a date when the ship is already occupied

activate System

System --> Adm: Shows the warning

deactivate System

deactivate Adm
@enduml