@startuml
actor "Ship Captain" as Adm
participant ":NumberCargoManifestAvgContainerUI" as System
participant ":NumberCargoManifestAvgContainerController" as SSC
participant ":US207" as us
participant ":FileOperation" as f

autonumber

activate Adm

Adm -> System: request to know how many cargo manifests I have transported

activate System

System --> Adm: asks for the year

deactivate System

Adm -> System: types the data requested

activate System

System -> SSC: createUS207

activate SSC

SSC -> us: demo(mmsi, year)

activate us

us -> us: initialize

us -> f: WriteToAFile(path, data)

deactivate us

activate f

f --> SSC: file

deactivate f

SSC --> System: file

System --> Adm: shows the requested data

deactivate SSC

deactivate System

deactivate Adm
@enduml