@startuml
actor "Port Manager" as Adm
participant "System" as System

autonumber

activate Adm

Adm -> System: Port manager issues a cargo manifest destined for a warehouse whose available capacity is insufficient to accommodate the new manifest

activate System

System --> Adm: Shows the warning

deactivate System

deactivate Adm
@enduml