@startuml
actor "Ship Captain" as Adm
participant ":OccupanceRateGivenShipDateUI" as System
participant ":OccupanceRateGivenShipDateController" as SSC
participant ":US209" as us
participant ":FileOperation" as f

autonumber

activate Adm

Adm -> System: request to know the occupancy rate of a ship

activate System

System --> Adm: asks for a ship

deactivate System

Adm -> System: types the data requested

activate System

System -> SSC: createUS209

activate SSC

SSC -> us: demo(mmsi, date)

activate us

us -> us: initialize

us -> f: WriteToAFile(path, data)

deactivate us

activate f

f --> SSC: file

deactivate f

SSC --> System: file

System --> Adm: shows the requested data

deactivate SSC

deactivate System

deactivate Adm
@enduml