@startuml
US412Controller ..> Company
US412Controller ..> Energy
US412Controller ..> ContainerStore
US412Controller ..> Container
Company ..> ContainerStore

US412Controller : +energyToSupply()

Energy : -heatFlow
Energy : -energy
Energy : +energyToSupply()

Company : +getContainerStore()

Container : +getArea()
Container : +getL1()
Container : +getL2()
Container : +getL3()
Container : +getK1()
Container : +getK2()
Container : +getK3()

ContainerStore : +getContainerList()


@enduml